### ISSUE TITLE
Wrong "content-type" header

### ISSUE THREAD

**Issue by parshap** [jhiesey/stream-http#8] opened 2015-08-05 23:38 UTC
I'm seeing an issue in Safari 8 where `response.headers["content-type"]` is `"text/plain; charset=x-user-defined"` when the server actually sent `text/javascript; charset=utf-8` (which I can confirm the the developer tools network pane).

It looks like the content-type header gets overridden here: https://github.com/jhiesey/stream-http/blob/aeabb2cc707d66580a5e9f8ad6ea6719c26498a6/lib/request.js#L148 — but I am not sure why.

**Comment by jhiesey** [comment] 2015-08-06 03:31
Darn! Seems obvious now that you mention it.

Calling `overrideMimeType` is necessary to not corrupt binary data that is streamed in. I'll have to think about what the best long-term solution is for this.

In the meantime, as a workaround, you can pass `options.mode = 'prefer-fast'`. That will avoid the call to `overrideMimeType`.

**Comment by parshap** [comment] 2015-08-06 07:38
> Calling `overrideMimeType` is necessary to not corrupt binary data that is streamed in. I'll have to think about what the best long-term solution is for this.

I couldn't find a way to access the original `content-type` header if `overrideMimeType` was called and [the spec doesn't seem to mention anything](https://xhr.spec.whatwg.org/#response-mime-type).

**Comment by jhiesey** [comment] 2015-08-07 05:35
Yeah, the spec is a bit vague. I think I was assuming that the actual `content-type

**Comment by parshap** [comment] 2015-08-11 17:12
Yes, using `prefer-fast` gives the correct `content-type` header. But I'm actually using @substack's [substack/hyperquest][] which uses `stream-http` via browserify but doesn't expose a way to pass the `mode` option, so I've had to downgrade browserify to before the change to `stream-http` for now.

I think there's a lot of modules out there that depend on *exactly* the node http interface, and so I think it would be best if `overrideMimeType` is not used unless an explicit flag is passed in signaling the developer knows to expect an incorrect `content-type` header.

[substack/hyperquest]: https://github.com/substack/hyperquest

**Comment by jhiesey** [comment] 2015-08-11 19:56
@parshap you make a good point. I definitely do need to fix this one way or another.

The original motivation for this module was to provide streaming in all possible circumstances. Providing the `http` module in browserify (and hence matching the `http` interface exactly) was a later decision. In other words, streaming was a more important goal to me than matching the api exactly. I realize this conflicts with being the default implementation of `http` in browserify.

How about this: I'll make a new module (http-browserify-stream?) that uses this module and provides the same interface, but with different defaults; in particular, it will preserve `content-type` by default. I will then submit a PR to browserify so that it uses `http-browserify-stream` instead of `stream-http` directly.

@feross @substack thoughts?

**Comment by parshap** [comment] 2015-08-11 20:03
> The original motivation for this module was to provide streaming in all possible circumstances. Providing the http module in browserify (and hence matching the http interface exactly) was a later decision. In other words, streaming was a more important goal to me than matching the api exactly.

Understandable.

> How about this: I'll make a new module (http-browserify-stream?) that uses this module and provides the same interface, but with different defaults; in particular, it will preserve content-type by default. I will then submit a PR to browserify so that it uses http-browserify-stream instead of stream-http directly.

This sounds like a great compromise! I'm happy to help in any way I can.

**Comment by jhiesey** [comment] 2015-08-20 07:07
After some more thinking, I decided that disabling streaming on Safari by default is not that big of a deal, since it has a fairly small market share and it's easy enough to turn it back on when using the module directly.

The fix should be released in the next day or two.

**Closed** 2015-08-20 08:21 UTC

**Comment by jhiesey** [comment] 2015-08-20 08:50
Should be fixed

**Comment by revolunet** [comment] 2015-08-28 00:20
hey :) About the "fairly small market share"... you forget iOS : every single iphone/ipad around + cordova web applications :)

Not sure if this is related but i may have been hit by this here : https://gist.github.com/revolunet/4417e4168ae2879a3604 can you confirm ? 

thanks !

**Comment by revolunet** [comment] 2015-08-28 00:34
downgraded to 1.4.0 for testing but still the same result... i dont have any idea whats going on :/

**Comment by parshap** [comment] 2015-08-28 01:29
@jhiesey: I finally got a chance to upgrade to 1.5.0 and test issue and it is indeed fixed in Safari. Thanks! 

(This is unrelated to @revolunet's issue.)

**Comment by jhiesey** [comment] 2015-08-28 06:11
@revolunet I was (perhaps short-sightedly) thinking mostly of browsers that support streaming video through the mediasource extensions, which doesn't include mobile safari.

Actually getting the data as soon as possible isn't important that often, but video is one case where it can help a lot.

**Comment by feross** [comment] 2015-08-28 17:28
@revolunet this issue is about the content-type http header. The issue in your gist looks like something completely differnet.

**Comment by revolunet** [comment] 2015-08-29 14:36
Yes excuse me for the noise here, i still have no idea where the bug come from... will produce a new gist today with reproducible example in a separate issue.

**Comment by revolunet** [comment] 2015-08-29 16:37
well no idea if this is the correct repo for this issue... heres a reproductible test case : https://github.com/revolunet/browserify-request-base64-issue

1) running in the browser gives incorrect base64
2) for some reason i have to force `new Buffer(body, 'binary').toString('base64')` in browserify to make the b64 conversion. `body.toString('base64')` works fine in Node though.

So i suspect something wrong in browserify/http

any help appreciated

**Comment by jhiesey** [comment] 2015-08-29 19:17
@revolunet I looked through the bundle.js file you supplied (https://raw.githubusercontent.com/revolunet/browserify-request-base64-issue/master/bundle.js) and it's definitely not generated with browserify 11.

And I *can* reproduce your issue if I explicitly install browserify@10.2.6.

I can see that the http module inside the bundle is actually the old [`http-browserify`](https://github.com/substack/http-browserify), not `stream-http` (the repo this bug is on). That was the default implementation before version 11, and also explains why you need `new Buffer(body, 'binary')`. The necessity of doing that with the old implementation was one of my motivations for writing a replacement.

My guess is that you have more than one version of browserify installed. Please run `browserify --version` to see what version you're actually getting when you are generating the bundle. You probably have an older version installed globally, which is getting picked up in your PATH, and a newer version installed that you aren't using.

To get the non-global version that you probably want to use, you need to run
```
node_modules/.bin/browserify ./src/index.js -o ./bundle.js
```
instead of
```
browserify ./src/index.js -o ./bundle.js
```

Alternatively, you can add the browserify command to the `"scripts"` section of the package.json and the correct version of browserify will be used automatically.

**Comment by revolunet** [comment] 2015-08-29 19:59
OMG what a noob i am, you nailed it, i indeed have a global browserify and it was used when calling `browserify` directly.

My apologies for the noise here and many thanks for your kind and effective support.

npm global modules are evil, lesson learnt the hard way... 

current status : 

![global](https://i.imgflip.com/q9xvz.jpg)

**Comment by feross** [comment] 2015-08-29 23:13
@jhiesey doing it like a boss

![](http://media.tumblr.com/1287fae040c1a81e4799afb5da9f4d85/tumblr_inline_mg4bkzre5H1r3h2hc.gif)
