### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by mrft** [jhiesey/stream-http#34] opened 2016-01-08 11:56 UTC
Might be related to #29 

I was writing a browser app using Ionic and testing on Android 4.0.3, using browserify so I could use needle for http requests in the browser.

It worked until I tried to fetch a url like http://data.flightradar24.com/_external/planedata_json.1.4.php?f=87ae8b0&equip_hint=A320&format=2

And I could see an error being logged on the console pointing stream-http/lib/response.js to "IncomingMessage.prototype._onXHRProgress = function() { ... }" the line containing self.push(...). The error was  *Uncaught TypeError: Type error*

<pre>
		case 'arraybuffer':
			if (xhr.readyState !== rStates.DONE)
				break
			response = xhr.response
			self.push(new Buffer(new Uint8Array(response)))
			break
</pre>

That's all I know, just wanted to let you know.

**Comment by jhiesey** [comment] 2016-01-08 18:13
I should fix it so that line doesn't throw an exception, but you won't be able to fetch that url from the browser because it lacks the right [cors headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

Unless the API provides these headers or a jsonp version you'll have to make requests like these from the server side due to the same origin policy.

**Comment by parshap** [comment] 2016-01-08 18:35
I think this may also be the same error I reported in #11.

**Comment by jhiesey** [comment] 2016-01-08 19:45
@parshap do you mean #20?

**Comment by jhiesey** [comment] 2016-01-08 19:49
Is there also an `error` event fired on the response? When I checked with the url supplied by @mrft I saw one of those as well.

If that's the issue, it may be solved by the change I made in https://github.com/jhiesey/stream-http/commit/570f85ec18e63f3aea3b49c6685780cc585edb05 but forgot to push/publish.

**Comment by parshap** [comment] 2016-01-08 20:27
Sorry, yes I meant #20. I'm not sure about an error event as I'm only seeing this error captured by New Relic monitoring and don't really have more info. I haven't seen it happen much.

**Comment by jhiesey** [comment] 2016-01-08 22:10
I agree that this is probably a duplicate of #20, and I hope it's fixed as of stream-http@2.0.3. Feel free to reopen if the issue is still present.

**Closed by jhiesey** 2016-01-08 22:10 UTC
